#!/usr/bin/env php
<?php

declare(strict_types=1);

use Psr\Log\NullLogger;

use G41797\Queue\Valkey\Adapter;

use G41797\Queue\Valkey\Support\FileHelper;
use G41797\Queue\Valkey\Support\SimpleMessageHandler;

use Symfony\Component\Console\Application;

use Yiisoft\Injector\Injector;

use Yiisoft\Test\Support\Container\SimpleContainer;

use Yiisoft\Queue\Cli\SignalLoop;
use Yiisoft\Queue\Command\ListenCommand;
use Yiisoft\Queue\Middleware\CallableFactory;
use Yiisoft\Queue\Middleware\Consume\ConsumeMiddlewareDispatcher;
use Yiisoft\Queue\Middleware\Consume\MiddlewareFactoryConsume;
use Yiisoft\Queue\Middleware\FailureHandling\FailureMiddlewareDispatcher;
use Yiisoft\Queue\Middleware\FailureHandling\MiddlewareFactoryFailure;
use Yiisoft\Queue\Middleware\Push\MiddlewareFactoryPush;
use Yiisoft\Queue\Middleware\Push\PushMiddlewareDispatcher;
use Yiisoft\Queue\Queue;
use Yiisoft\Queue\QueueFactory;
use Yiisoft\Queue\Adapter\AdapterInterface;

require_once dirname(__DIR__) . '/vendor/autoload.php';

$logger = new NullLogger();
$container = new SimpleContainer([]);
$injector = new Injector($container);
$callableFactory = new CallableFactory($container);
$worker = new \Yiisoft\Queue\Worker\Worker(
    [
        'simple' => new SimpleMessageHandler(new FileHelper()),
    ],
    $logger,
    $injector,
    $container,
    new ConsumeMiddlewareDispatcher(new MiddlewareFactoryConsume($container, $callableFactory)),
    new FailureMiddlewareDispatcher(new MiddlewareFactoryFailure($container, $callableFactory), []),
);
$loop = new SignalLoop();
$pushMiddlewareDispatcher = new PushMiddlewareDispatcher(new MiddlewareFactoryPush($container, $callableFactory));
$adapter = Adapter::default(logger: $logger, loop: $loop);
$queue = new Queue(
    $worker,
    $loop,
    $logger,
    $pushMiddlewareDispatcher,
    $adapter,
);
$queueFactory = new QueueFactory(
    [],
    $queue,
    $container,
    $callableFactory,
    $injector,
);

$application = new Application();
$application->add(new ListenCommand($queueFactory));
$application->run();
